"""Prepare simulated input for ALTitude.

Converts the simulated CSV (test_data.txt) into the TSV format ALTitude
expects: tab-separated, with a binary `ALT` target column. The fake file
already has the telomere features ALTitude needs (TelSeq,
TelFusDetector_rate, TelFuse_newtelomere, and the 56 TVR columns) plus
metadata columns the pipeline auto-drops.

The synthetic features were generated by generate_fake_complete.py
(on the geelegrp volume) using a hidden 50/50 ALT vector drawn by
`np.random.default_rng(42)` then `rng.shuffle`. This script reproduces
that *exact* vector (same N=100, same 50/50 layout, same seed, same
shuffle), so the ALT column we attach here matches the labels the
features were sampled from. Result: trained models recover the
injected signal (AUC ≈ 1.0 across base models on LOO-CV) — this is a
real signal recovery test, not just an end-to-end smoke test.

Usage (run with the miniconda Python that has numpy/pandas/sklearn/xgboost/etc.):
    ~/miniconda3/bin/python prepare_fake_data.py
    ~/miniconda3/bin/python prepare_fake_data.py --input test_data.txt --output fake_alt.tsv --seed 42
"""

import argparse
from pathlib import Path

import numpy as np
import pandas as pd


def prepare(input_path: Path, output_path: Path, seed: int) -> pd.DataFrame:
    df = pd.read_csv(input_path, sep=",")

    n = len(df)
    rng = np.random.default_rng(seed)
    labels = np.zeros(n, dtype=int)
    labels[: n // 2] = 1
    rng.shuffle(labels)
    df.insert(0, "ALT", labels)

    df.to_csv(output_path, sep="\t", index=False)
    return df


def main() -> None:
    here = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=here / "test_data.txt")
    parser.add_argument("--output", type=Path, default=here / "fake_alt_input.tsv")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    df = prepare(args.input, args.output, args.seed)

    pos = int((df["ALT"] == 1).sum())
    neg = int((df["ALT"] == 0).sum())
    print(f"Wrote {args.output} : {len(df)} samples, {len(df.columns)} columns")
    print(f"  ALT=1: {pos}  ALT=0: {neg}")
    print(f"\nNext:  ~/miniconda3/bin/python ALTitude_cli.py train {args.output} --output-dir ./test/results --loo-cv")


if __name__ == "__main__":
    main()
